---
title: "Plant observation map"
author: "Dennis Amnebrink"
format: 
  html:
    embed-resources: true
editor: visual
---


```{r}
#| echo: false
#| warning: false
# Libraries
library(leaflet)
library(leaflet.extras2)
library(htmlwidgets)
library(tidyverse)
library(renv)
library(leafpop)
library(sf)
library(glue)
library(kableExtra)
```

```{r}
#| echo: false
#| warning: false
 # Data loading
#Getting pathname and filename from directory, as it changes every time you export your .csv file, for this to work you must put have this document in a folder called "analysis", this directory should be in the same directory as another directory called "Data". In the data directory you put the unzipped version of your downloaded .zip-file from flora incognita.

pathname = list.dirs(path = "../Data/", recursive = FALSE)
filename = list.files(path = pathname, pattern = ".csv")

 
dat <- read.csv(paste0(pathname, "/",filename), header=TRUE)  %>%
  filter(!is.na(longitude)) %>% # Removing observations without coordinates
  mutate(PicLoc  =  paste0(pathname, "/",date,"/",date,"-0.jpg")) %>% # Picture Location for each observation 
  mutate(newname =  paste0("<iframe  src=","'", PicLoc,"'", ">", "</iframe>")) %>%
   separate(scientific.name, c("Genus", "Species"),sep= " " , remove = FALSE, extra = "merge")
```

This dataset contains   `r nrow(dat) ` FloraIncognita observations covering `r length(unique(dat$scientific.name))` species from  `r length(unique(dat$Genus))` genera. Each observation has a popup for the name, and an accompanying circle which displays the picture.

```{r}
#| echo: false
#| eval: false
# Creating the map with clustered observations, not used as it could not include pictures for some reason
map1 <- leaflet(data = dat)   %>%
  addProviderTiles('OpenStreetMap.Mapnik' )  %>%
  addCircleMarkers(lng = ~longitude, lat = ~latitude,
          label = ~paste(scientific.name, name, sep = ", "),
          radius=7, 
          labelOptions = labelOptions(style = list("color" = "black"), 
                  noHide = T, textOnly=T, textsize = "10px", offset = c(1, 12)), 
          color="black",clusterOptions = markerClusterOptions(spiderfyOnMaxZoom=F)) %>%
addPopupImages(img, group = "pnt2")

 

map1

saveWidget(map1, file="../Results/map.html")


```


```{r}
#| echo: false
#| eval: false
### Playing around
data2 <- dat[c(1,2),c(1,2,3,4,5,6,7,8)]
  

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = breweries91,
                   popup = popupTable(breweries91))

pnt = st_as_sf(data.frame(x = 174.764474, y = -36.877245),
                coords = c("x", "y"),
                crs = 4326)

pnt2 = st_as_sf(data.frame(x = data2$latitude , y = data2$longitude),
                coords = c('x', 'y'),
                crs = 4326)

img = c("../Data/flora_incognita_2025-07-29T17_58_10/2025-06-13T13_56_53Z/2025-06-13T13_56_53Z-0.jpg","../Data/flora_incognita_2025-07-29T17_58_10/2025-06-13T13_56_53Z/2025-06-13T13_56_53Z-0.jpg")

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = pnt2, group = "pnt2") %>%
  addPopupImages(img, group = "pnt2")
```

```{r}
#| echo: false
#| eval: false
### This is working, keep it

pnt2 = st_as_sf(data.frame(x = dat$longitude , y = dat$latitude),
                coords = c('x', 'y'),
                crs = 4326)
img = dat$PicLoc

map1 = leaflet(data = dat) %>%
  addTiles() %>%
 addCircleMarkers( lng = ~longitude, lat = ~latitude, popup = id,
          label = ~paste(scientific.name, name, sep = ", "),
          radius=7,
          labelOptions = labelOptions(style = list("color" = "black"), 
                  noHide = T, textOnly=T, textsize = "10px")
          #,clusterOptions = markerClusterOptions(spiderfyOnMaxZoom=F) # Works better without clustering
          ) %>% 
  addCircleMarkers(data = pnt2, group = "pnt2") %>%
  addPopupImages(img, group = "pnt2", width = 400, height = 400) 

map1

saveWidget(map1, file="../Results/map.html")
```

```{r}
#| echo: false
#| label: fig-map
#| fig-cap: "Map of observations paired markers contain species name and picture."

label_text <- glue(
  "<b>Scientific name: </b> <i> {dat$scientific.name}</i><br/>",
  "<b>Swedish name: </b> {dat$name}<br/>") %>%
  lapply(htmltools::HTML)

pnt2 = st_as_sf(data.frame(x = dat$longitude , y = dat$latitude),
                coords = c('x', 'y'),
                crs = 4326)
img = dat$PicLoc

map1 = leaflet(data = dat) %>%
  addTiles() %>%
  addMarkers(~longitude, ~latitude, popup = label_text) %>% 
  addCircleMarkers(data = pnt2, group = "pnt2") %>%
  addPopupImages(img, group = "pnt2", width = 400, height = 400) 


map1

saveWidget(map1, file="../Results/map.html")
```

```{r}
#| echo: false
#| label: tbl-overview
#| tbl-cap: "Table containing all different species of this dataset, arranged alphabetically by genus."
kable(dat %>% distinct(Genus, Species, name) %>% arrange(Genus)) %>% 
   kable_styling(font_size = 8) %>% 
scroll_box(width = "500px", height = "400px")
```

```{r}
#| echo: false
#| eval: false
#Trying to create a UI to filter with shiny

label_text <- glue(
  "<b>Scientific name: </b> <i> {dat$scientific.name}</i><br/>",
  "<b>Swedish name: </b> {dat$name}<br/>") %>%
  lapply(htmltools::HTML)

pnt2 = st_as_sf(data.frame(x = dat$longitude , y = dat$latitude),
                coords = c('x', 'y'),
                crs = 4326)
img = dat$PicLoc

data = dat
# UI
# UI

ui <- fluidPage(
  titlePanel("Searchable Leaflet Map"),
  sidebarLayout(
    sidebarPanel(
      selectInput("Genus", "Filter by Genus:", 
                  choices = c("All", unique(data$Genus)), 
                  selected = "All")
    ),
    mainPanel(
      leafletOutput("map")
    )
  )
)

# Server
server <- function(input, output, session) {
  filteredData <- reactive({
    if (input$Genus == "All") {
      data
    } else {
      subset(data, Genus == input$Genus)
    }
  })
  
  output$map <- renderLeaflet({
    leaflet(data) %>%
      addTiles() %>%
      addMarkers(~longitude, ~latitude, popup = label_text) %>% 
  addCircleMarkers(data = pnt2, group = "pnt2") %>%
  addPopupImages(img, group = "pnt2", width = 400, height = 400) 
  })
  
  observe({
    leafletProxy("map", data = filteredData()) %>%
      clearMarkers() %>%
      addMarkers(~longitude, ~latitude, popup = label_text) %>% 
  addCircleMarkers(data = pnt2, group = "pnt2") %>%
  addPopupImages(img, group = "pnt2", width = 400, height = 400) 
  })
}

# Run the app
shinyApp(ui, server)


```
\
\
\
Original code provided by flora incognita at https://floraincognita.com/wp-content/uploads/2023/07/R_MapExport_EN.txt
